language: python
python:
  - "3.6"
sudo: required
services:
  - docker
env:
  - DOCKER_COMPOSE_VERSION=1.21.2
before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
# command to install dependencies
install:
  - python3 --version
  - pip3 install -r requirements.txt
  - pip3 list
# command to run tests
script:
  - chmod +x script_run_docker.sh
  - ./script_run_docker.sh
  - pytest -s -v test_album.py
  - pytest -s -v test_album_favorite.py
  - pytest -s -v test_album_user.py
  - pytest -s -v test_other.py
  - ./script_run_docker.sh
  - pytest -s -v test_delete.py
  - ./script_run_docker.sh
  - pytest -s -v test_sharing_with_album_token_no_permission.py
  - ./script_run_docker.sh
  - pytest -s -v test_sharing_with_album_token.py
  - ./script_run_docker.sh
  - pytest -s -v test_report_providers.py
  