name: CI Test

on:
  push:
    branches: [ master ]
  schedule:
    - cron: '0 22 * * 1-5'
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Run Kheops on docker
        run: | 
         chmod +x script_run_docker.sh
         ./script_run_docker.sh
           
      - uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: Install python and pytest 
        run: |
          python -m pip install --upgrade pip
          pip3 install -r requirements.txt

      - name: Run test_register_in_keycloak
        run: pytest -s -v test_register_in_keycloak.py
      - name: Run test_karnak
        run: pytest -s -v test_karnak.py
      - name: Run test_link
        run: pytest -s -v test_link.py
      - name: Run test_album
        run: pytest -s -v test_album.py
      - name: Run test_album_favorite
        run: pytest -s -v test_album_favorite.py
      - name: Run test_album_user
        run: pytest -s -v test_album_user.py
      - name: Run test_album_event
        run: pytest -s -v test_album_event.py
      - name: Run test_album_sharing
        run: pytest -s -v test_album_sharing.py
      - name: Run test_other
        run: pytest -s -v test_other.py
      - name: Run test_sharing_with_album_token
        run: pytest -s -v test_sharing_with_album_token.py
        continue-on-error: true
      - name: Run test_sharing_with_album_token_no_permission
        run: pytest -s -v test_sharing_with_album_token_no_permission.py
      - name: Run test_report_providers
        run: pytest -s -v test_report_providers.py
      - name: Run test_delete
        run: pytest -s -v test_delete.py
      - name: Run test_webhook
        run: pytest -s -v test_webhook.py

