# This is a basic workflow to help you get started with Actions

name: CI Test

on:
  push:
    branches: [ master ]
  schedule:
    - cron: '0 22 * * 1-5'
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Run Kheops on docker
        run: | 
         chmod +x script_run_docker.sh
         ./script_run_docker.sh
           
      - uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: Install python and pytest 
        run: |
          python -m pip install --upgrade pip
          pip3 install -r requirements.txt


      #- uses: cclauss/GitHub-Action-for-pytest@0.5.0
      - name: Run test
        run: | 
          pytest -s -v test_register_in_keycloak.py
          pytest -s -v test_karnak.py
          pytest -s -v test_link.py
          pytest -s -v test_album.py
          pytest -s -v test_album_favorite.py
          pytest -s -v test_album_user.py
          pytest -s -v test_album_event.py
          pytest -s -v test_album_sharing.py
          pytest -s -v test_other.py
          pytest -s -v test_sharing_with_album_token.py
          pytest -s -v test_sharing_with_album_token_no_permission.py
          pytest -s -v test_report_providers.py
          pytest -s -v test_delete.py
          pytest -s -v test_webhook.py

