# This is a basic workflow to help you get started with Actions

name: CI Test


on:
  push:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run1
        run: chmod +x script_run_docker.sh
      - name: Run2
        run: ./script_run_docker.sh
      - uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: install python and pytest 
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      #- uses: cclauss/GitHub-Action-for-pytest@0.5.0
      - name: run test
        run: pytest -s -v test_register_in_keycloak.py
