# This is a basic workflow to help you get started with Actions

name: CI Test


on:
  push:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Runs a set of commands using the runners shell
      #- name: Run Kheops on docker
      #  run: | 
      #   chmod +x script_run_docker.sh
      #   ./script_run_docker.sh
         
      - uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: install python and pytest 
        run: |
          python3 --version
          python -m pip3 install --upgrade pip3
          pip3 install -r requirements.txt
          pip3 list

      #- uses: cclauss/GitHub-Action-for-pytest@0.5.0
      - name: run test
        run: pytest -s -v test_register_in_keycloak.py
      - name: run test2
        run: pytest -s -v test_album.py
